version: "3.8"
services:
  postgres:
    image: bitnami/postgresql
    container_name: popsales-database
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/bitnami/postgresql
    env_file:
      - .env

volumes:
  postgres_data:
    driver: local
